spring:
  application:
    name: notification-service
  config:
    import: "configserver:http://localhost:19000"
  cloud:
    config:
      name: notification-service
      profile: dev
      fail-fast: true